# write-config.ps1 - Generate a minimal zeroclaw config.toml during MSI install.
# Called by the WiX custom action with properties collected from the installer UI.

param(
    [string]$ApiKey = "",
    [string]$Provider = "openrouter",
    [string]$ActivityArn = ""
)

$configDir = Join-Path $env:USERPROFILE ".zeroclaw"
$configFile = Join-Path $configDir "config.toml"

# Don't overwrite an existing config
if (Test-Path $configFile) {
    Write-Host "Config already exists at $configFile — skipping."
    exit 0
}

# Create directory
if (-not (Test-Path $configDir)) {
    New-Item -ItemType Directory -Path $configDir -Force | Out-Null
}

# Pick a sensible default model per provider
$model = switch ($Provider) {
    "anthropic"  { "claude-sonnet-4-20250514" }
    "openai"     { "gpt-4o" }
    "gemini"     { "gemini-2.0-flash" }
    default      { "anthropic/claude-sonnet-4" }
}

# Build config content
$config = @"
# ZeroClaw configuration — generated by LocalAgent installer.
# Edit this file or run `zeroclaw onboard --interactive` for full setup.

api_key = "$ApiKey"
default_provider = "$Provider"
default_model = "$model"
default_temperature = 0.7

[memory]
backend = "sqlite"
auto_save = true

[autonomy]
level = "Supervised"
workspace_only = true

[heartbeat]
enabled = true
interval_minutes = 5

"@

# Activity channel (only if ARN provided)
if ($ActivityArn -and $ActivityArn -ne "") {
    $config += @"

[channels_config.activity]
activity_arn = "$ActivityArn"
worker_name = "zeroclaw"
heartbeat_interval_secs = 30
poll_interval_ms = 1000

"@
}

# Bundled MCP servers
$config += @"

[[mcp_servers]]
name = "config-server"
transport = "http"
url = "http://localhost:3100/mcp"
enabled = true

[[mcp_servers]]
name = "browser-server"
transport = "http"
url = "http://localhost:3200/mcp"
enabled = true
"@

Set-Content -Path $configFile -Value $config -Encoding UTF8
Write-Host "Config written to $configFile"
