# write-config.ps1 - Generate a minimal zeroclaw config.toml during MSI install.
# Called by the WiX custom action with properties collected from the installer UI.
# Note: MSI custom actions run as SYSTEM, so we detect the real user profile.

param(
    [string]$ApiKey = "",
    [string]$Provider = "openrouter",
    [string]$ActivityArn = ""
)

$logFile = Join-Path $env:TEMP "zeroclaw-install.log"

function Log($msg) {
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "$ts $msg" | Out-File -Append -FilePath $logFile
}

try {
    Log "write-config.ps1 started"
    Log "USERPROFILE=$env:USERPROFILE"
    Log "Provider=$Provider, ApiKey length=$($ApiKey.Length), ActivityArn=$ActivityArn"

    # Detect the actual logged-in user's profile.
    # MSI server process runs as SYSTEM, so $env:USERPROFILE points to the
    # SYSTEM profile, not the installing user.
    $userProfile = $env:USERPROFILE
    if ($userProfile -like '*systemprofile*' -or $userProfile -like '*system32*' -or $userProfile -like '*SYSTEM*') {
        Log "Running as SYSTEM, detecting logged-in user..."
        $loggedOn = (Get-CimInstance -ClassName Win32_ComputerSystem).UserName
        if ($loggedOn) {
            $username = $loggedOn.Split('\')[-1]
            $userProfile = Join-Path "C:\Users" $username
            Log "Detected user: $loggedOn -> profile: $userProfile"
        } else {
            Log "WARNING: Could not detect logged-in user, using USERPROFILE"
        }
    }

    $configDir = Join-Path $userProfile ".zeroclaw"
    $configFile = Join-Path $configDir "config.toml"
    Log "Config target: $configFile"

    # Don't overwrite an existing config
    if (Test-Path $configFile) {
        Log "Config already exists - skipping."
        Write-Host "Config already exists at $configFile - skipping."
        exit 0
    }

    # Create directory
    if (-not (Test-Path $configDir)) {
        New-Item -ItemType Directory -Path $configDir -Force | Out-Null
        Log "Created directory: $configDir"
    }

    # Pick a sensible default model per provider
    $model = switch ($Provider) {
        "anthropic"  { "claude-sonnet-4-20250514" }
        "openai"     { "gpt-4o" }
        "gemini"     { "gemini-2.0-flash" }
        default      { "anthropic/claude-sonnet-4" }
    }

    # Build config content
    $config = @"
# ZeroClaw configuration - generated by LocalAgent installer.
# Edit this file or run ``zeroclaw onboard --interactive`` for full setup.

api_key = "$ApiKey"
default_provider = "$Provider"
default_model = "$model"
default_temperature = 0.7

[memory]
backend = "sqlite"
auto_save = true

[autonomy]
level = "Supervised"
workspace_only = true

[heartbeat]
enabled = true
interval_minutes = 5

"@

    # Activity channel (only if ARN provided)
    if ($ActivityArn -and $ActivityArn -ne "") {
        $config += @"

[channels_config.activity]
activity_arn = "$ActivityArn"
worker_name = "zeroclaw"
heartbeat_interval_secs = 30
poll_interval_ms = 1000

"@
    }

    # Bundled MCP servers
    $config += @"

[[mcp_servers]]
name = "config-server"
transport = "http"
url = "http://localhost:3100"
enabled = true

[[mcp_servers]]
name = "browser-server"
transport = "http"
url = "http://localhost:3200"
enabled = true
"@

    Set-Content -Path $configFile -Value $config -Encoding UTF8
    Log "Config written successfully to $configFile"
    Write-Host "Config written to $configFile"
}
catch {
    Log "ERROR: $_"
    Log "Stack: $($_.ScriptStackTrace)"
    Write-Error $_
    exit 1
}
